# Generated by Django 2.2.12 on 2020-04-05 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='普通会员表',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('昵称', models.CharField(blank=True, max_length=50)),
                ('身份', models.CharField(max_length=2)),
                ('用户', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '普通会员表',
            },
        ),
        migrations.DeleteModel(
            name='教师',
        ),
    ]
