# Generated by Django 2.2.12 on 2020-04-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20200405_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('teacherName', models.CharField(max_length=10)),
                ('courseNum', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=10)),
            ],
        ),
    ]
