# Generated by Django 2.2.12 on 2020-04-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='courseNum',
            field=models.CharField(max_length=10),
        ),
    ]
