# Generated by Django 2.2.12 on 2020-05-15 15:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Login', '0006_asscourse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='普通会员表',
            new_name='normaluserform',
        ),
        migrations.AlterModelOptions(
            name='normaluserform',
            options={'verbose_name_plural': 'normaluserform'},
        ),
    ]
