# Generated by Django 2.2.12 on 2020-05-15 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_auto_20200515_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='normaluserform',
            old_name='身份',
            new_name='Identity',
        ),
        migrations.RenameField(
            model_name='normaluserform',
            old_name='用户',
            new_name='USER',
        ),
        migrations.RenameField(
            model_name='normaluserform',
            old_name='昵称',
            new_name='nickname',
        ),
    ]
