# Generated by Django 2.2.12 on 2020-04-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('courseNum', models.CharField(max_length=10, null=True)),
                ('headImg', models.FileField(upload_to='./files/')),
            ],
        ),
    ]
