# Generated by Django 2.2.12 on 2020-05-05 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeworkPublish', '0006_auto_20200502_2011'),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='courseNum',
        ),
        migrations.AddField(
            model_name='userfile',
            name='homework',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='HomeworkPublish.Homework'),
            preserve_default=False,
        ),
    ]
