# Generated by Django 2.2 on 2020-04-13 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Homework_text', models.TextField()),
                ('Pub_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.DateTimeField()),
            ],
        ),
    ]
