# Generated by Django 2.2 on 2020-04-14 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeworkPublish', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ('Pub_time',)},
        ),
    ]
