# Generated by Django 2.2 on 2020-04-16 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeworkPublish', '0002_auto_20200414_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ('-Pub_time',)},
        ),
    ]
