# Generated by Django 2.2.12 on 2020-04-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeworkPublish', '0004_homework_coursenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='courseNum',
            field=models.IntegerField(),
        ),
    ]
