# Generated by Django 2.2 on 2020-05-02 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HomeworkPublish', '0005_auto_20200430_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='deadline',
        ),
        migrations.AddField(
            model_name='homework',
            name='deadline_date',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homework',
            name='deadline_time',
            field=models.TextField(default='23:59'),
        ),
    ]
