# Generated by Django 2.2.11 on 2020-05-12 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20200505_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='homework',
            new_name='userfile',
        ),
    ]
