# Generated by Django 2.2.12 on 2020-05-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20200512_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentator',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
